params:
  seed: ${...seed}

  algo:
    name: morph_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True

    mlp:
      units: ${resolve_default:[1024, 512, 256, 128],${.....mlp}}
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:Dog,${....experiment}}
    device: ${....rl_device}
    full_experiment_name: ${.name}
    train_dir: ${....output_path}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    reward_shaper:
      scale_value: 0.01
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: ${resolve_default:500,${....max_iterations}}
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 16
    minibatch_rate: ${resolve_default:0.5,${....minibatch_rate}}
    minibatch_size: ${resolve_default:32768,${....minibatch_size}}
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    print_stats: ${resolve_default:True,${....print_stats}}
    save_network:  ${resolve_default:True,${....save_network}}
    save_summary:  ${resolve_default:False,${....save_summary}}

    games_to_track: ${resolve_default:128,${....games_to_track}}
